# Ordered by output of `jazzy --help config`
output: ../docs
title: My first autogendoc project
clean: true
objc: false
xcodebuild_arguments: 
- -scheme 
- AutoDocumentation 
- CODE_SIGNING_ALLOWED = NO
# umbrella_header: 
# framework_root: .
module: AutoDocumentation
module_version: 1.2.3
author: mirav!ng
copyright: Copyright 2016 mirav!ng.
sdk: iphonesimulator
author_url: https://github.com/miraving
github_url: https://github.com/miraving/autodocumentation
# github_file_prefix: https://github.com/miraving/autodocumentation
skip_undocumented: true
hide_documentation_coverage: false
# use_safe_filenames: true
theme: fullwidth
# exclude: 
min_acl: internal