module: AutoDocumentation
author: miraving
author_url: https://github.com/miraving
github_url: https://github.com/miraving/autodocumentation
framework_root: /
output: ../docs
title: My first autogendoc project
clean: true
sdk: iphonesimulator
skip_undocumented: true
hide_documentation_coverage: false
theme: fullwidth
# min_acl: internal
exclude: